[package]
name = "envcaja"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
aes-gcm = "0.10.3"
base64 = "0.22.1"
rand = "0.9.2"
clap = { version = "4.5.48", features = ["derive", "env"] }
