name: Release envbuddel

on:
  push:
    tags:
      - 'v*'  # nur bei Tag-Pushes wie v0.1.0 auslösen

permissions:
  contents: write  # für GitHub Release nötig

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: cargo-build-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "envbuddel ${{ github.ref_name }}"
          body: "Automated release from tag ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/envbuddel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
